# Generated by Django 5.0.4 on 2024-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltage_level',
            field=models.CharField(choices=[('12~48', '12~48'), ('110', '110'), ('220', '220'), ('110 ~ 240', '110 ~ 240'), ('415', '415'), ('N/A', 'N/A')], max_length=20),
        ),
    ]
